#!/usr/bin/env perl

# Perl utility for starting a Jupyter notebook in the current directory.

# First inquires for the list of running notebook servers. If one is running
# in the current directory, open a web page to it. If none are running, start
# one in the background.

use Cwd;

my $argc = $#ARGV+1;
if ($argc) {
    my $cmd = $ARGV[0];
    if ($cmd eq "list") {
        print "\n";
        system("jupyter notebook list");
        print "\n";
    }
    else {
        print "failed to understand command '$cmd'\n";
    }
    exit();
}

my $cwd = getcwd;

my @lines = split /\n/, `jupyter notebook list`;
foreach (@lines) {
    chomp;             
    if (/::/) {
        my @t = split /\s+::\s+/;
        if ($t[1] eq $cwd) {
            print "opening Jupyter notebook at ${t[0]}\n";
            system("open", $t[0]);
            exit();
        }
    }
}
# No server existing server found, so start one
system("jupyter notebook 2>>.juplog &")


# Could possibly use the --json flag, which emits lines
# of the form
# { "notebook_dir": "/Users/jeunice/pytest/testing/codement1",
#   "secure": false,
#   "pid": 52284,
#   "base_url": "/",
#   "url": "http://localhost:8888/",
#   "port": 8888,
#   "hostname": "localhost"
# }
# while these are well-formed records, the output as a whole is
# not wrapped in an array, and is therefore not JSON as a whole
